accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout')
]

attendance/urls.py
from django.urls import path
from . import views

app_name = 'attendance'
urlpatterns = [
    path('', views.index, name='index'),
    path('result/', views.result, name='result'),
]

test_1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('attendance.urls')),
    path('admin/', admin.site.urls),
]

accounts/models.py
from django.db import models

# Create your models here.

attendance/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
import datetime as dt
from django.utils import timezone

# Create your models here.


class SubmitAttendance(models.Model):

    class Meta:
        db_table = 'attendance'

    PLACES = (
        (1, '東京'),
        (2, '大阪'),
        (3, '名古屋'),
        (4, '福岡'),
        (5, '札幌'),
        (6, '沖縄'),
    )
    IN_OUT = (
        (1, '出勤'),
        (0, '退勤'),
    )

    staff = models.ForeignKey(
        get_user_model(), verbose_name="スタッフ", on_delete=models.CASCADE, default=None)
    place = models.IntegerField(
        verbose_name='出勤場所名', choices=PLACES, default=None)
    in_out = models.IntegerField(
        verbose_name='IN/OUT', choices=IN_OUT, default=None)
    time = models.TimeField(verbose_name="打刻時間")
    date = models.DateField(verbose_name='打刻日')

    # 辞書化
    place_dict = dict(PLACES)
    in_out_dict = dict(IN_OUT)

    def __str__(self):
        return str(User.objects.get(id=self.staff_id)) + ' : ' + str(self.place_dict[self.place]) + ' ' + str(self.in_out_dict[self.in_out])

attendance/forms.py

from django import forms
from .models import SubmitAttendance


class SubmitAttendanceForm(forms.ModelForm):

    class Meta:
        model = SubmitAttendance
        fields = ('place', 'in_out')

accounts/views.py
from django.shortcuts import render

# Create your views here.

attendance/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import SubmitAttendance
from .forms import SubmitAttendanceForm
from datetime import datetime
from django.utils import timezone
# Create your views here.


class IndexView(LoginRequiredMixin, View):
    def get(self, request):
        form = SubmitAttendanceForm
        context = {
            'form': form,
            "user": request.user,
        }
        return render(request, 'attendance/index.html', context)


index = IndexView.as_view()


class ResultView(View):
    def post(self, request):
        form = SubmitAttendanceForm(request.POST)
        now = datetime.now()
        month = now.month
        day = now.day
        hour = now.hour
        minute = now.minute

        obj = form.save(commit=False)
        obj.place = request.POST["place"]
        obj.in_out = request.POST["in_out"]
        obj.staff = request.user
        obj.date = datetime.now().date()
        obj.time = datetime.now().time()
        obj.save()
        if request.POST["in_out"] == '1':
            comment = str(month) + "月" + str(day) + "日" + str(hour) + \
                "時" + str(minute) + "分\n" + "出勤確認しました。今日も頑張りましょう！"
        else:
            comment = str(month) + "月" + str(day) + "日" + str(hour) + \
                "時" + str(minute) + "分\n" + "退勤確認しました。お疲れ様でした(^-^)！"
        context = {
            'place': SubmitAttendance.PLACES[int(obj.place)-1][1],
            'comment': comment,
        }
        return render(request, 'attendance/result.html', context)


result = ResultView.as_view()

attendance/templates/attendance/base.html

{% load static %}
<html>
<head>
    <meta charset='utf-8'>
    <link rel="stylesheet" type="text/css" href="{% static 'attendance/css/style.css' %}">
    <title>勤怠打刻ページ</title>
</head>
<body>
    {% block content  %}
    {% endblock  %}
</body>
</html>

attendance/templates/attendance/index.html

{% extends "attendance/base.html" %}
{% block content %}

{% if user.is_authenticated %}
<div class="container">
    <form method="post" action="{% url 'attendance:result' %}">
        {% csrf_token %}
        <h1>{{  user  }} さん</h1>
        <h2 id="time"></h2>
        <script>
            time();
            function time() {
                var now = new Date();
                document.getElementById("time").innerHTML = now.toLocaleString();
            }
            setInterval('time()', 1000);
        </script>
        <p>出勤場所：<input type="hidden" name="place">{{ form.place }}</p>
        <p>IN/OUT：<input type="hidden" name="in_out">{{ form.in_out }}</p>
        <p><input class="btn btn-primary" type="submit" value="Submit"></p>
    </form>
    <a href="../accounts/logout">ログアウト</a>
</div>
{% endif %}
{% endblock  %}

attendance/templates/attendance/result.html

{% extends 'attendance/base.html' %}
{% block content %}
<p>出勤場所：{{ place }}</p>
<p>{{ comment }}</p>
<a href="../accounts/logout">ログアウト</a>
{% endblock  %}